'use strict';
// A dependency-free adapter, generated directly from the authoritative CJS files.
// No rules are maintained in the UI, and the originals retain their Node exports.
const fs = require('node:fs');
const path = require('node:path');
function build() {
  const modules = ['ColorSpace', 'HarmonyGrammar', 'CompoundHarmony', 'ColorHarmonyEngine'];
  const source = modules.map(name => `${JSON.stringify('./'+name+'.js')}: (module, exports, require) => {\n${fs.readFileSync(path.join(__dirname, '..', name+'.js'), 'utf8')}\n}`).join(',\n');
  const result = `// Generated by build.js. Do not edit. Source: ../ engine modules.\nconst factories = {${source}};\nconst cache = {};\nfunction require(id) {\n if (!factories[id]) throw new Error('Unknown engine module: '+id);\n if (!cache[id]) { const module = {exports:{}}; cache[id]=module; factories[id](module,module.exports,require); }\n return cache[id].exports;\n}\nexport const ColorSpace = require('./ColorSpace.js');\nexport default require('./ColorHarmonyEngine.js');\n`;
  fs.writeFileSync(path.join(__dirname, 'engine.generated.mjs'), result);
}
module.exports = { build };
if (require.main === module) build();
